/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.CT_KhuyenMaiBUS;
import BUS.KhachHangBUS;
import BUS.NhanVienBUS;
import BUS.SanPhamBUS;
import DTO.KhachHang;
import DTO.NhanVien;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agond
 */
public class PhanQuyen extends javax.swing.JFrame {
    int pos = 0, stt_nv = 0, stt_kh = 0;
    private String filename;
    Properties props = null;
    SanPhamBUS spBUS;
    KhachHangBUS khBUS;
    NhanVienBUS nvBUS;
    KhachHang kh;
    NhanVien nv;
    private ArrayList<KhachHang> list_kh; 
    private ArrayList<NhanVien> list_nv; 
    /**
     * Creates new form MuaHang
     */
    public PhanQuyen() throws IOException, ClassNotFoundException, SQLException {
        initComponents();
        setLocationRelativeTo(null);
        this.filename = "src\\DTO\\MaxID.txt";
        this.props = new Properties();
        props.load(new FileReader(filename));
        
        spBUS = new SanPhamBUS();
        khBUS = new KhachHangBUS();
        nvBUS = new NhanVienBUS();   
        
        list_kh = new ArrayList<>(khBUS.getList());
        list_nv = new ArrayList<>(nvBUS.getList());
    }
    
    public void initClick_KH() throws IOException{
        pos = this.tbCTKM1.getSelectedRow();
        
        if(pos != -1){
            String user = (String) tbCTKM1.getValueAt(pos, 3);
            kh =  khBUS.searchObjectByUsername(user);
            txtHoLot1.setText(kh.getHoLot());
            txtTen1.setText(kh.getTen());
            txtDiaChi1.setText(kh.getDiaChi());
            txtSDT1.setText(kh.getSDT());
            txtUsername1.setText(kh.getUsername());
        }
    }
    
    public void initClick_NV(){
        pos = this.tbCTKM3.getSelectedRow();
        
        if(pos != -1){
            String user = (String) tbCTKM3.getValueAt(pos, 3);
            nv = nvBUS.searchObjectByUsername(user);
            txtHoLot2.setText(nv.getHoLot());
            txtTen2.setText(nv.getTen());
            txtDiaChi2.setText(nv.getDiaChi());
            txtSDT2.setText(nv.getSDT());
            txtUsername2.setText(nv.getUsername());
            txtLuong.setText(String.valueOf(nv.getLuong()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNav = new javax.swing.JPanel();
        lblPhoneStore = new javax.swing.JLabel();
        btnMuaHang = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnKhuyenMai = new javax.swing.JButton();
        btnPhanQuyen = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbCTKM3 = new javax.swing.JTable();
        txtDiaChi2 = new javax.swing.JTextField();
        txtPass2 = new javax.swing.JPasswordField();
        txtHoLot2 = new javax.swing.JTextField();
        btnDelete2 = new javax.swing.JButton();
        txtConfirmPass2 = new javax.swing.JPasswordField();
        lblUsername2 = new javax.swing.JLabel();
        btnSignup2 = new javax.swing.JButton();
        lblHoLot2 = new javax.swing.JLabel();
        txtSDT2 = new javax.swing.JTextField();
        btnUpdate2 = new javax.swing.JButton();
        txtTen2 = new javax.swing.JTextField();
        lblTen2 = new javax.swing.JLabel();
        lblPass2 = new javax.swing.JLabel();
        lblDiaChi2 = new javax.swing.JLabel();
        lblConfirmPass2 = new javax.swing.JLabel();
        txtUsername2 = new javax.swing.JTextField();
        lblSDT4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        lblSDT5 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCTKM1 = new javax.swing.JTable();
        lblConfirmPass1 = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPass1 = new javax.swing.JPasswordField();
        btnDelete1 = new javax.swing.JButton();
        lblUsername1 = new javax.swing.JLabel();
        lblHoLot1 = new javax.swing.JLabel();
        btnUpdate1 = new javax.swing.JButton();
        lblTen1 = new javax.swing.JLabel();
        lblDiaChi1 = new javax.swing.JLabel();
        lblSDT3 = new javax.swing.JLabel();
        txtDiaChi1 = new javax.swing.JTextField();
        txtHoLot1 = new javax.swing.JTextField();
        txtConfirmPass1 = new javax.swing.JPasswordField();
        btnSignup1 = new javax.swing.JButton();
        txtSDT1 = new javax.swing.JTextField();
        txtTen1 = new javax.swing.JTextField();
        lblPass1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PhoneStore: Khuyến mãi");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnNav.setBackground(new java.awt.Color(50, 50, 50));

        lblPhoneStore.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPhoneStore.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneStore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoneStore.setLabelFor(pnNav);
        lblPhoneStore.setText("Phonestore");

        btnMuaHang.setBackground(new java.awt.Color(240, 240, 240));
        btnMuaHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMuaHang.setForeground(new java.awt.Color(75, 75, 75));
        btnMuaHang.setText("Mua hàng");
        btnMuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuaHangActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(240, 240, 240));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(75, 75, 75));
        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnSanPham.setBackground(new java.awt.Color(240, 240, 240));
        btnSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSanPham.setForeground(new java.awt.Color(75, 75, 75));
        btnSanPham.setText("Sản Phẩm");

        btnKhuyenMai.setBackground(new java.awt.Color(240, 240, 240));
        btnKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKhuyenMai.setForeground(new java.awt.Color(75, 75, 75));
        btnKhuyenMai.setText("Khuyến mãi");
        btnKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhuyenMaiActionPerformed(evt);
            }
        });

        btnPhanQuyen.setBackground(new java.awt.Color(60, 90, 180));
        btnPhanQuyen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPhanQuyen.setForeground(new java.awt.Color(240, 240, 240));
        btnPhanQuyen.setText("Phân quyền");

        btnDangXuat.setBackground(new java.awt.Color(50, 50, 50));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(240, 240, 240));
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnNavLayout = new javax.swing.GroupLayout(pnNav);
        pnNav.setLayout(pnNavLayout);
        pnNavLayout.setHorizontalGroup(
            pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNavLayout.createSequentialGroup()
                .addGroup(pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNavLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMuaHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKhuyenMai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(btnPhanQuyen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnNavLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblPhoneStore, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator3)
        );
        pnNavLayout.setVerticalGroup(
            pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNavLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblPhoneStore)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnMuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPhanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        tbCTKM3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Họ lót", "Tên", "Username", "Lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCTKM3.setMinimumSize(new java.awt.Dimension(12, 0));
        tbCTKM3.setRowHeight(28);
        tbCTKM3.setSelectionBackground(new java.awt.Color(60, 90, 180));
        tbCTKM3.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tbCTKM3.setShowGrid(false);
        tbCTKM3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCTKM3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbCTKM3);
        if (tbCTKM3.getColumnModel().getColumnCount() > 0) {
            tbCTKM3.getColumnModel().getColumn(0).setPreferredWidth(8);
            tbCTKM3.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbCTKM3.getColumnModel().getColumn(3).setPreferredWidth(20);
            tbCTKM3.getColumnModel().getColumn(4).setPreferredWidth(12);
            tbCTKM3.getColumnModel().getColumn(4).setHeaderValue("Lương");
        }

        txtDiaChi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChi2ActionPerformed(evt);
            }
        });

        txtPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass2ActionPerformed(evt);
            }
        });

        txtHoLot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoLot2ActionPerformed(evt);
            }
        });

        btnDelete2.setBackground(new java.awt.Color(242, 242, 242));
        btnDelete2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete2.setForeground(new java.awt.Color(25, 25, 25));
        btnDelete2.setText("Xóa");
        btnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete2ActionPerformed(evt);
            }
        });

        txtConfirmPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPass2ActionPerformed(evt);
            }
        });

        lblUsername2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername2.setForeground(new java.awt.Color(25, 25, 25));
        lblUsername2.setText("Tên đăng nhập");

        btnSignup2.setBackground(new java.awt.Color(25, 25, 25));
        btnSignup2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignup2.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup2.setText("Đăng ký");
        btnSignup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignup2ActionPerformed(evt);
            }
        });

        lblHoLot2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHoLot2.setForeground(new java.awt.Color(25, 25, 25));
        lblHoLot2.setText("Họ và tên đệm");

        txtSDT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDT2ActionPerformed(evt);
            }
        });

        btnUpdate2.setBackground(new java.awt.Color(242, 242, 242));
        btnUpdate2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate2.setForeground(new java.awt.Color(25, 25, 25));
        btnUpdate2.setText("Sửa");
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });

        txtTen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTen2ActionPerformed(evt);
            }
        });

        lblTen2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTen2.setForeground(new java.awt.Color(25, 25, 25));
        lblTen2.setText("Tên");

        lblPass2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPass2.setForeground(new java.awt.Color(25, 25, 25));
        lblPass2.setText("Mật khẩu");

        lblDiaChi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDiaChi2.setForeground(new java.awt.Color(25, 25, 25));
        lblDiaChi2.setText("Địa chỉ");

        lblConfirmPass2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblConfirmPass2.setForeground(new java.awt.Color(25, 25, 25));
        lblConfirmPass2.setText("Xác nhận");

        txtUsername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername2ActionPerformed(evt);
            }
        });

        lblSDT4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT4.setForeground(new java.awt.Color(25, 25, 25));
        lblSDT4.setText("Số điện thoại");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Thông tin chi tiết");

        txtLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuongActionPerformed(evt);
            }
        });

        lblSDT5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT5.setForeground(new java.awt.Color(25, 25, 25));
        lblSDT5.setText("Lương");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(btnDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSignup2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHoLot2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoLot2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(lblTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtTen2)))
                    .addComponent(txtDiaChi2)
                    .addComponent(txtSDT2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(lblUsername2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtUsername2))
                        .addGap(18, 18, 18)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSDT5)
                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChi2)
                            .addComponent(lblSDT4)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblConfirmPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtConfirmPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoLot2)
                    .addComponent(lblTen2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoLot2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiaChi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiaChi2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSDT4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSDT2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(lblSDT5)
                        .addGap(5, 5, 5)
                        .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(lblUsername2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass2)
                    .addComponent(lblConfirmPass2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSignup2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhân viên", panel2);

        tbCTKM1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Họ lót", "Tên", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCTKM1.setMinimumSize(new java.awt.Dimension(12, 0));
        tbCTKM1.setRowHeight(28);
        tbCTKM1.setSelectionBackground(new java.awt.Color(60, 90, 180));
        tbCTKM1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tbCTKM1.setShowGrid(false);
        tbCTKM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCTKM1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCTKM1);
        if (tbCTKM1.getColumnModel().getColumnCount() > 0) {
            tbCTKM1.getColumnModel().getColumn(0).setPreferredWidth(8);
            tbCTKM1.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbCTKM1.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        lblConfirmPass1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblConfirmPass1.setForeground(new java.awt.Color(25, 25, 25));
        lblConfirmPass1.setText("Xác nhận");

        txtUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Thông tin chi tiết");

        txtPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass1ActionPerformed(evt);
            }
        });

        btnDelete1.setBackground(new java.awt.Color(242, 242, 242));
        btnDelete1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete1.setForeground(new java.awt.Color(25, 25, 25));
        btnDelete1.setText("Xóa");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(25, 25, 25));
        lblUsername1.setText("Tên đăng nhập");

        lblHoLot1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHoLot1.setForeground(new java.awt.Color(25, 25, 25));
        lblHoLot1.setText("Họ và tên đệm");

        btnUpdate1.setBackground(new java.awt.Color(242, 242, 242));
        btnUpdate1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(25, 25, 25));
        btnUpdate1.setText("Sửa");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        lblTen1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTen1.setForeground(new java.awt.Color(25, 25, 25));
        lblTen1.setText("Tên");

        lblDiaChi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDiaChi1.setForeground(new java.awt.Color(25, 25, 25));
        lblDiaChi1.setText("Địa chỉ");

        lblSDT3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT3.setForeground(new java.awt.Color(25, 25, 25));
        lblSDT3.setText("Số điện thoại");

        txtDiaChi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChi1ActionPerformed(evt);
            }
        });

        txtHoLot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoLot1ActionPerformed(evt);
            }
        });

        txtConfirmPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPass1ActionPerformed(evt);
            }
        });

        btnSignup1.setBackground(new java.awt.Color(25, 25, 25));
        btnSignup1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignup1.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup1.setText("Đăng ký");
        btnSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignup1ActionPerformed(evt);
            }
        });

        txtSDT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDT1ActionPerformed(evt);
            }
        });

        txtTen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTen1ActionPerformed(evt);
            }
        });

        lblPass1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPass1.setForeground(new java.awt.Color(25, 25, 25));
        lblPass1.setText("Mật khẩu");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSignup1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChi1)
                            .addComponent(lblSDT3)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtConfirmPass1)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(lblConfirmPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 36, Short.MAX_VALUE))))
                            .addComponent(txtSDT1)
                            .addComponent(txtUsername1)
                            .addComponent(lblUsername1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHoLot1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoLot1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(lblTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtTen1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)))
                            .addComponent(txtDiaChi1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoLot1)
                    .addComponent(lblTen1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoLot1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiaChi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiaChi1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSDT3)
                .addGap(5, 5, 5)
                .addComponent(txtSDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass1)
                    .addComponent(lblConfirmPass1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignup1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Khách hàng", panel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        Index indexForm = new Index(); 
        indexForm.setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnMuaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuaHangActionPerformed
        MuaHang muaHangForm = null; 
        try {
            muaHangForm = new MuaHang();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
        muaHangForm.setVisible(true); // Hiển thị form "Signin"
        this.dispose(); // Ẩn form hiện tại (Signup)
    }//GEN-LAST:event_btnMuaHangActionPerformed

    private void btnKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhuyenMaiActionPerformed
        KhuyenMai khuyenMaiForm = null; 
        try {
            khuyenMaiForm = new KhuyenMai();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
        khuyenMaiForm.setVisible(true); // Hiển thị form "Signin"
        this.dispose(); // Ẩn form hiện tại (MuaHang)
    }//GEN-LAST:event_btnKhuyenMaiActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        ThongKe thongKeForm = null; 
        try {
            thongKeForm = new ThongKe();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
        thongKeForm.setVisible(true); // Hiển thị form "Signin"
        this.dispose(); // Ẩn form hiện tại (MuaHang)
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void tbCTKM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCTKM1MouseClicked
        try {
            initClick_KH();
        } catch (IOException ex) {
            Logger.getLogger(PhanQuyen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbCTKM1MouseClicked

    private void tbCTKM3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCTKM3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCTKM3MouseClicked

    private void txtUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername1ActionPerformed

    private void txtPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        int pos = this.tbCTKM1.getSelectedRow();
        if(pos == -1){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn khách hàng cần xóa.");
        } else {
            KhachHang kh_del = khBUS.searchObjectByUsername(txtUsername1.getText());
            boolean chk_del = khBUS.delete(kh_del);
            if(chk_del){
                JOptionPane.showMessageDialog(null, "Xóa khách hàng " + kh_del.getUsername() + " thành công");
                //Cập nhật bảng
                DefaultTableModel model = (DefaultTableModel) tbCTKM1.getModel();
                model.removeRow(pos);
                int row = tbCTKM1.getRowCount();
                for(int i = 1; i < row; i++){
                    model.setValueAt(i, i, 0);
                }
            } else JOptionPane.showMessageDialog(null, "Xóa thất bại.");
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        try {
            // TODO add your handling code here:
            boolean chk_input_blank = checkTextFieldInputs_Blank(panel1);
            if(chk_input_blank) {
                if(txtPass1.getText().equals(txtConfirmPass1.getText())){
                    KhachHang chk = new KhachHang();
                    chk.setHoLot(txtHoLot1.getText());
                    chk.setTen(txtTen1.getText());
                    chk.setDiaChi(txtDiaChi1.getText());
                    chk.setSDT(txtSDT1.getText());
                    chk.setUsername(txtUsername1.getText());
                    chk.setPassword(txtPass1.getText());

                    boolean chk_update = khBUS.update(chk);
                    
                    if(chk_update){
                        JOptionPane.showMessageDialog(null, "Đăng kí khách hàng thành công.");
                        //Cập nhật bảng
                        DefaultTableModel model = (DefaultTableModel) tbCTKM1.getModel();
                        int column_user = 3;
                        int rowCount = model.getRowCount();
                        for(int i=0; i < rowCount; i++){
                            String user = (String) model.getValueAt(i, column_user);
                            if(chk.getUsername().equals(user)){
                                model.setValueAt(chk.getHoLot(), i, 1);
                                model.setValueAt(chk.getTen(), i, 2);
                                break;
                            }
                        }
                    } else JOptionPane.showMessageDialog(null, "Đăng kí khách hàng không thành công.");                
                }
            } else JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin khách hàng.");
        } catch (IOException ex) {
            Logger.getLogger(PhanQuyen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void txtDiaChi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChi1ActionPerformed

    private void txtHoLot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoLot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoLot1ActionPerformed

    private void txtConfirmPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPass1ActionPerformed

    private void btnSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignup1ActionPerformed
        try {
            // TODO add your handling code here:
            boolean chk_input_blank = checkTextFieldInputs_Blank(panel1);
            if(chk_input_blank) {
                KhachHang chk = new KhachHang();
                chk.setHoLot(txtHoLot1.getText());
                chk.setTen(txtTen1.getText());
                chk.setDiaChi(txtDiaChi1.getText());
                chk.setSDT(txtSDT1.getText());
                chk.setUsername(txtUsername1.getText());
                chk.setPassword(txtPass1.getText());

                int chk_unique = khBUS.write(chk, txtConfirmPass1.getText());
                
                if(chk_unique == 1){
                    JOptionPane.showMessageDialog(null, "Username đã tồn tại trong hệ thống.");
                } else if(chk_unique == 2){
                    JOptionPane.showMessageDialog(null, "Xác nhận mật khẩu không đúng.");
                } else {
                    DefaultTableModel model = (DefaultTableModel) tbCTKM1.getModel();
                    Object[] rowdata = {stt_kh++, kh.getHoLot(), kh.getTen(), kh.getUsername()};
                    model.addRow(rowdata);
                    JOptionPane.showMessageDialog(null, "Đăng kí khách hàng thành công.");
                }
            } else JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin khách hàng.");
        } catch (IOException ex) {
            Logger.getLogger(PhanQuyen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSignup1ActionPerformed

    private void txtSDT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDT1ActionPerformed

    private void txtTen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTen1ActionPerformed

    private void txtDiaChi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChi2ActionPerformed

    private void txtPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass2ActionPerformed

    private void txtHoLot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoLot2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoLot2ActionPerformed

    private void btnDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete2ActionPerformed
        // TODO add your handling code here:
        int pos = this.tbCTKM3.getSelectedRow();
        if(pos == -1){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn nhân viên cần xóa.");
        } else {
            NhanVien nv_del = nvBUS.searchObjectByUsername(txtUsername2.getText());
            boolean chk_del = nvBUS.delete(nv_del);
            if(chk_del){
                JOptionPane.showMessageDialog(null, "Xóa nhân viên " + nv_del.getUsername() + " thành công");
                //Cập nhật bảng
                DefaultTableModel model = (DefaultTableModel) tbCTKM3.getModel();
                model.removeRow(pos);
                int row = tbCTKM3.getRowCount();
                for(int i = 1; i < row; i++){
                    model.setValueAt(i, i, 0);
                }
            } else JOptionPane.showMessageDialog(null, "Xóa thất bại.");
        }
    }//GEN-LAST:event_btnDelete2ActionPerformed

    private void txtConfirmPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPass2ActionPerformed

    private void btnSignup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignup2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            boolean chk_input_blank = checkTextFieldInputs_Blank(panel2);
            if(chk_input_blank) {
                NhanVien chk = new NhanVien();
                chk.setHoLot(txtHoLot2.getText());
                chk.setTen(txtTen2.getText());
                chk.setDiaChi(txtDiaChi2.getText());
                chk.setSDT(txtSDT2.getText());
                chk.setLuong(Integer.parseInt(txtLuong.getText()));
                chk.setUsername(txtUsername2.getText());
                chk.setPassword(txtPass2.getText());

                int chk_unique = nvBUS.write(chk, txtConfirmPass2.getText());
                
                if(chk_unique == 1){
                    JOptionPane.showMessageDialog(null, "Username đã tồn tại trong hệ thống.");
                } else if(chk_unique == 2){
                    JOptionPane.showMessageDialog(null, "Xác nhận mật khẩu không đúng.");
                } else {
                    DefaultTableModel model = (DefaultTableModel) tbCTKM3.getModel();
                    Object[] rowdata = {stt_nv++, nv.getHoLot(), nv.getTen(), nv.getUsername(), nv.getLuong()};
                    model.addRow(rowdata);
                    JOptionPane.showMessageDialog(null, "Đăng kí nhân viên thành công.");
                }
            } else JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin nhân viên.");
        } catch (IOException ex) {
            Logger.getLogger(PhanQuyen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSignup2ActionPerformed

    private void txtSDT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDT2ActionPerformed

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            boolean chk_input_blank = checkTextFieldInputs_Blank(panel2);
            if(chk_input_blank) {
                if(txtPass2.getText().equals(txtConfirmPass2.getText())){
                    NhanVien chk = new NhanVien();
                    chk.setHoLot(txtHoLot2.getText());
                    chk.setTen(txtTen2.getText());
                    chk.setDiaChi(txtDiaChi2.getText());
                    chk.setSDT(txtSDT2.getText());
                    chk.setLuong(Integer.parseInt(txtLuong.getText()));
                    chk.setUsername(txtUsername2.getText());
                    chk.setPassword(txtPass2.getText());

                    boolean chk_update = nvBUS.update(chk);
                    
                    if(chk_update){
                        JOptionPane.showMessageDialog(null, "Đăng kí nhân viên thành công.");
                        //Cập nhật bảng
                        DefaultTableModel model = (DefaultTableModel) tbCTKM3.getModel();
                        int column_user = 3;
                        int rowCount = model.getRowCount();
                        for(int i=0; i < rowCount; i++){
                            String user = (String) model.getValueAt(i, column_user);
                            if(chk.getUsername().equals(user)){
                                model.setValueAt(chk.getHoLot(), i, 1);
                                model.setValueAt(chk.getTen(), i, 2);
                                model.setValueAt(chk.getLuong(), i, 4);
                                break;
                            }
                        }
                    } else JOptionPane.showMessageDialog(null, "Đăng kí khách hàng không thành công.");                
                }
            } else JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin khách hàng.");
        } catch (IOException ex) {
            Logger.getLogger(PhanQuyen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void txtTen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTen2ActionPerformed

    private void txtUsername2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername2ActionPerformed

    private void txtLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuongActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) tbCTKM1.getModel();
        for(KhachHang kh : list_kh){
            Object[] rowdata1 = {stt_kh++, kh.getHoLot(), kh.getTen(), kh.getUsername()};
            model1.addRow(rowdata1);
        }
        
        DefaultTableModel model2 = (DefaultTableModel) tbCTKM3.getModel();
        for(NhanVien nv : list_nv){
            Object[] rowdata2 = {stt_nv++, nv.getHoLot(), nv.getHoLot(), nv.getUsername(), nv.getLuong()};
            model2.addRow(rowdata2);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PhanQuyen().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(PhanQuyen.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PhanQuyen.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(PhanQuyen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    
    //Kiểm tra các textfield có đang chọn hay ko
    public boolean checkTextFieldInputs_Blank(Container container) {
        for(Component c : getComponents()){
            if(c instanceof JTextField){
                JTextField txt = (JTextField) c;
                if(txt.getText().isEmpty()){
                    return true;
                }
            }
        }
        return false;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnKhuyenMai;
    private javax.swing.JButton btnMuaHang;
    private javax.swing.JButton btnPhanQuyen;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnSignup1;
    private javax.swing.JButton btnSignup2;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblConfirmPass1;
    private javax.swing.JLabel lblConfirmPass2;
    private javax.swing.JLabel lblDiaChi1;
    private javax.swing.JLabel lblDiaChi2;
    private javax.swing.JLabel lblHoLot1;
    private javax.swing.JLabel lblHoLot2;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JLabel lblPass2;
    private javax.swing.JLabel lblPhoneStore;
    private javax.swing.JLabel lblSDT3;
    private javax.swing.JLabel lblSDT4;
    private javax.swing.JLabel lblSDT5;
    private javax.swing.JLabel lblTen1;
    private javax.swing.JLabel lblTen2;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel pnNav;
    private javax.swing.JTable tbCTKM1;
    private javax.swing.JTable tbCTKM3;
    private javax.swing.JPasswordField txtConfirmPass1;
    private javax.swing.JPasswordField txtConfirmPass2;
    private javax.swing.JTextField txtDiaChi1;
    private javax.swing.JTextField txtDiaChi2;
    private javax.swing.JTextField txtHoLot1;
    private javax.swing.JTextField txtHoLot2;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPass2;
    private javax.swing.JTextField txtSDT1;
    private javax.swing.JTextField txtSDT2;
    private javax.swing.JTextField txtTen1;
    private javax.swing.JTextField txtTen2;
    private javax.swing.JTextField txtUsername1;
    private javax.swing.JTextField txtUsername2;
    // End of variables declaration//GEN-END:variables
}
